name: Vantage Lead Gen Bot

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Scraper and AI
        run: python bot.py
        env:
          # دي أهم خطوة: بنقول للبوت خد المفتاح من الخزنة
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

      - name: Save Leads
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add leads.csv
          git commit -m "AI Analyzed Leads Found" || exit 0
          git push
